'use client';

import React, { useState } from 'react';

const initialNotifications = [
  { id: '1', type: 'rewards', title: 'Low Reward Inventory Alert', desc: 'Vantage Electronics - "Wireless Charger" stock has fallen below threshold of 10. Current stock: 8.', time: '10 mins ago', read: false },
  { id: '2', type: 'rotations', title: 'Partner Rotation Initiated', desc: 'Meridian Apparel is now the primary storefront spotlight partner. Weekly rotation successfully deployed.', time: '1 hour ago', read: false },
  { id: '3', type: 'leads', title: 'High-Value Lead Captured', desc: 'Alessandro Rossi (a.rossi@outlook.it) completed Summer Spin campaign. Routed to Meridian Apparel CRM.', time: '3 hours ago', read: false },
  { id: '4', type: 'campaigns', title: 'New Campaign Draft Created', desc: 'Campaign "Holiday Engagement Push" has been successfully initialized as draft.', time: 'Yesterday', read: true },
  { id: '5', type: 'system', title: 'Ecosystem API Key Regenerated', desc: 'A new production API key was generated by administrator account admin@mcomspin.com.', time: '2 days ago', read: true },
  { id: '6', type: 'rewards', title: 'Reward Redeemed', desc: 'Soleil Dining Group - "20% Off Dining" reward code successfully redeemed.', time: '2 days ago', read: true },
  { id: '7', type: 'partners', title: 'New Partner Invited', desc: 'Soleil Dining Group has accepted ecosystem invitation and connected their storefront.', time: '3 days ago', read: true },
  { id: '8', type: 'system', title: 'Monthly Integration Audit Passed', desc: 'Automated storefront audit completed successfully. 3 active domains verified healthy.', time: '4 days ago', read: true },
];

export default function NotificationsPage() {
  const [notifications, setNotifications] = useState(initialNotifications);
  const [filter, setFilter] = useState<'all' | 'campaigns' | 'rotations' | 'leads' | 'rewards' | 'system'>('all');

  const filteredNotifications = notifications.filter(n => {
    if (filter === 'all') return true;
    return n.type === filter;
  });

  const markAsRead = (id: string) => {
    setNotifications(prev =>
      prev.map(n => (n.id === id ? { ...n, read: true } : n))
    );
  };

  const markAllRead = () => {
    setNotifications(prev => prev.map(n => ({ ...n, read: true })));
  };

  const clearAll = () => {
    setNotifications([]);
  };

  const getIcon = (type: string) => {
    switch (type) {
      case 'rewards':
        return (
          <div className="p-2.5 bg-rose-50 text-rose-500 rounded-xl border border-rose-100">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M21 11.25v8.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5v-8.25M12 4.875A2.625 2.625 0 109.375 7.5H12m0-2.625A2.625 2.625 0 1114.625 7.5H12m0 0V21m-8.625-9.75h17.25" />
            </svg>
          </div>
        );
      case 'rotations':
        return (
          <div className="p-2.5 bg-amber-50 text-amber-500 rounded-xl border border-amber-100">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182m0-4.991v4.99" />
            </svg>
          </div>
        );
      case 'leads':
        return (
          <div className="p-2.5 bg-orange-50 text-[#f97316] rounded-xl border border-orange-100">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M19 7.5v3m0 0v3m0-3h3m-3 0h-3m-9-3.5h9.75M9 10.5h.008v.008H9V10.5zm0 3.5h.008v.008H9V14zm0 3.5h.008v.008H9V17.5z" />
            </svg>
          </div>
        );
      case 'campaigns':
        return (
          <div className="p-2.5 bg-emerald-50 text-emerald-500 rounded-xl border border-emerald-100">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 21l8.904-4.452L18 18l4.5-9-9 4.5 1.804 1.804z" />
            </svg>
          </div>
        );
      case 'system':
      default:
        return (
          <div className="p-2.5 bg-stone-100 text-stone-500 rounded-xl border border-stone-200">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 17.25v1.007a3 3 0 01-.879 2.122L7.5 21h9l-.621-.621A3 3 0 0115 18.257V17.25m6-12V15a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 15V5.25m18 0A2.25 2.25 0 0018.75 3H5.25A2.25 2.25 0 003 5.25m18 0V12a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 12V5.25" />
            </svg>
          </div>
        );
    }
  };

  return (
    <div className="space-y-8 pb-12">
      {/* Header & Bulk Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <p className="text-[10px] font-bold tracking-[0.15em] text-[#f97316] uppercase mb-1">Ecosystem</p>
          <h1 className="text-2xl font-display font-bold text-[#1a1a1a]">Notification Center</h1>
          <p className="text-[#888] text-[13px] mt-1">Real-time alerts, system triggers, and partner collaboration notifications.</p>
        </div>
        
        {notifications.length > 0 && (
          <div className="flex items-center gap-2">
            <button
              onClick={markAllRead}
              className="text-[11px] font-bold uppercase tracking-[0.08em] px-4 py-2 bg-[#f5f5f3] hover:bg-[#e2e2e0] text-[#1a1a1a] rounded-xl transition-all"
            >
              Mark All Read
            </button>
            <button
              onClick={clearAll}
              className="text-[11px] font-bold uppercase tracking-[0.08em] px-4 py-2 bg-stone-100 hover:bg-rose-50 hover:text-rose-600 text-stone-600 rounded-xl border border-stone-200 hover:border-rose-200 transition-all"
            >
              Clear All
            </button>
          </div>
        )}
      </div>

      {/* Tabs */}
      <div className="flex flex-wrap gap-1.5 p-1 bg-[#f5f5f3] rounded-xl w-max">
        {(['all', 'campaigns', 'rotations', 'leads', 'rewards', 'system'] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setFilter(tab)}
            className={`px-4 py-2 rounded-lg text-[11px] font-bold uppercase tracking-[0.08em] transition-all ${
              filter === tab
                ? 'bg-white text-[#1a1a1a] shadow-sm'
                : 'text-[#888] hover:text-[#555]'
            }`}
          >
            {tab}
          </button>
        ))}
      </div>

      {/* Notification List */}
      <div className="space-y-3">
        {filteredNotifications.length > 0 ? (
          filteredNotifications.map((notif) => (
            <div
              key={notif.id}
              className={`flex items-start justify-between gap-4 p-5 rounded-2xl bg-white border border-[#eee] transition-all hover:shadow-sm ${
                !notif.read ? 'border-l-4 border-l-[#f97316]' : ''
              }`}
            >
              <div className="flex items-start gap-4 flex-1">
                {getIcon(notif.type)}
                <div className="space-y-1">
                  <div className="flex items-center gap-2.5">
                    <h3 className={`text-[13px] font-bold ${!notif.read ? 'text-[#1a1a1a]' : 'text-[#666]'}`}>
                      {notif.title}
                    </h3>
                    {!notif.read && (
                      <span className="w-1.5 h-1.5 rounded-full bg-[#f97316] animate-ping" />
                    )}
                  </div>
                  <p className="text-[12px] text-[#888] leading-relaxed max-w-2xl">{notif.desc}</p>
                  <p className="text-[10px] text-[#bbb] font-semibold">{notif.time}</p>
                </div>
              </div>

              {!notif.read && (
                <button
                  onClick={() => markAsRead(notif.id)}
                  className="text-[10px] font-bold uppercase tracking-[0.08em] px-3 py-1.5 border border-[#eee] hover:border-[#1a1a1a] text-[#1a1a1a] rounded-lg transition-all"
                >
                  Mark Read
                </button>
              )}
            </div>
          ))
        ) : (
          <div className="flex flex-col items-center justify-center py-16 bg-stone-50 border border-dashed border-[#eee] rounded-2xl space-y-3 text-center">
            <div className="p-4 bg-white border border-[#eee] rounded-full text-[#bbb] shadow-sm">
              <svg className="w-8 h-8" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M14.857 17.082a9.041 9.041 0 01-1.857-.082c-1.8-.096-3.182-1.634-3.182-3.418v-3.9a4.5 4.5 0 019 0v3.9c0 1.784-1.382 3.322-3.182 3.418z" />
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 10.5a4.5 4.5 0 00-4.5 4.5v3a3 3 0 003 3h10.5a3 3 0 003-3v-3a4.5 4.5 0 00-4.5-4.5" />
              </svg>
            </div>
            <div>
              <p className="text-[13px] font-bold text-[#1a1a1a]">All caught up!</p>
              <p className="text-[#888] text-[12px]">No new notifications matching your filter.</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
