// tailwind.config.ts
import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'media',
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#cfe4ff",
        "outline": "#8e7164",
        "surface": "#fff8f6",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#541d00",
        "tertiary-container": "#009cf8",
        "surface-variant": "#f8ddd2",
        "on-background": "#261812",
        "secondary-fixed": "#ffdbcc",
        "on-tertiary-fixed-variant": "#004a79",
        "surface-container-low": "#fff1eb",
        "on-secondary-container": "#772f05",
        "on-primary": "#ffffff",
        "on-surface-variant": "#5a4136",
        "on-secondary-fixed-variant": "#793106",
        "secondary-container": "#ff9969",
        "on-surface": "#261812",
        "inverse-on-surface": "#ffede6",
        "error": "#ba1a1a",
        "surface-container": "#ffeae1",
        "on-primary-fixed-variant": "#7b2f00",
        "primary-fixed-dim": "#ffb695",
        "inverse-surface": "#3d2d26",
        "secondary": "#97471d",
        "primary": "#a23f00",
        "on-secondary-fixed": "#351000",
        "on-primary-fixed": "#351000",
        "surface-tint": "#a23f00",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ffb694",
        "on-tertiary-container": "#003152",
        "tertiary": "#00629f",
        "surface-container-highest": "#f8ddd2",
        "outline-variant": "#e2bfb1",
        "background": "#fff8f6",
        "surface-dim": "#efd5ca",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#001d34",
        "primary-container": "#fc6700",
        "surface-container-high": "#fee3d8",
        "surface-bright": "#fff8f6",
        "tertiary-fixed-dim": "#9acbff",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdbcc",
        "inverse-primary": "#ffb695",
        "error-container": "#ffdad6",
        // Keep existing ones for fallback if needed elsewhere
        bg: 'oklch(100% 0 0)',
        fg: 'oklch(20% 0.02 70)',
        muted: 'oklch(60% 0.01 70)',
        border: 'oklch(90% 0.01 70)',
        accent: 'oklch(65% 0.20 45)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px'
      },
      spacing: {
        "stack-sm": "8px",
        "gutter": "16px",
        "container-margin": "20px",
        "section-padding": "40px",
        "base": "8px",
        "stack-lg": "32px",
        "stack-md": "16px"
      },
      fontFamily: {
        display: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        body: ['Inter', '-apple-system', 'BlinkMacSystemFile', 'Segoe UI', 'Roboto', 'sans-serif'],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"]
      },
      fontSize: {
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
};
export default config;
